version: '3.8'

networks:
  default:
    external: true
    name: mainNetwork

services:
  mysql:
    image: mysql:latest
    container_name: invest-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
